name: Chanl
description: The chanl blog
meta_description: "Chanl app, blog posts"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://chanlapp.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://blog.chanlapp.com'
author:         'Team Chanl'
